-- Mediacloud source catalog. Lives in the `sources` schema of the sentinel
-- postgres database. Re-derivable: safe to drop and re-sync.
-- All tables use singular names. Booleans are BOOLEAN. ISO timestamps are
-- TIMESTAMPTZ (with the one exception of source.last_story which Mediacloud
-- returns in a non-ISO format).

CREATE SCHEMA IF NOT EXISTS sources;

CREATE TABLE IF NOT EXISTS sources.collection (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    notes TEXT,
    platform TEXT,
    source_count INTEGER,
    public BOOLEAN,
    featured BOOLEAN,
    managed BOOLEAN,
    monitored BOOLEAN,
    upstream_modified_at TIMESTAMPTZ,
    last_refreshed_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS sources.source (
    id INTEGER PRIMARY KEY,
    name TEXT,
    label TEXT,
    homepage TEXT,
    canonical_domain TEXT,
    platform TEXT,
    media_type TEXT,
    primary_language TEXT,
    pub_country TEXT,
    pub_state TEXT,
    stories_per_week INTEGER,
    stories_total INTEGER,
    collection_count INTEGER,
    monitored BOOLEAN,
    last_story TEXT,                 -- MC returns this in an irregular format
    upstream_created_at TIMESTAMPTZ,
    upstream_modified_at TIMESTAMPTZ,
    last_rescraped_at TIMESTAMPTZ,
    notes TEXT,
    alternative_domains JSONB,
    last_refreshed_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS source_canonical_domain ON sources.source(canonical_domain);
CREATE INDEX IF NOT EXISTS source_primary_language ON sources.source(primary_language);
CREATE INDEX IF NOT EXISTS source_pub_country ON sources.source(pub_country);
CREATE INDEX IF NOT EXISTS source_stories_per_week ON sources.source(stories_per_week);

-- Source <-> collection edges. Empty in v1 (membership not synced).
CREATE TABLE IF NOT EXISTS sources.source_collection (
    source_id INTEGER NOT NULL REFERENCES sources.source(id) ON DELETE CASCADE,
    collection_id INTEGER NOT NULL REFERENCES sources.collection(id) ON DELETE CASCADE,
    PRIMARY KEY (source_id, collection_id)
);

CREATE TABLE IF NOT EXISTS sources.sync_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    collections_synced INTEGER NOT NULL DEFAULT 0,
    sources_synced INTEGER NOT NULL DEFAULT 0,
    error TEXT
);

-- Validated Google News sitemap URLs discovered per source. One source
-- can have many rows (e.g. BBC has 3 numbered news shards; Asahi has 8
-- category sitemaps).
CREATE TABLE IF NOT EXISTS sources.source_sitemap (
    source_id INTEGER NOT NULL REFERENCES sources.source(id) ON DELETE CASCADE,
    sitemap_url TEXT NOT NULL,
    kind TEXT NOT NULL,                  -- 'news' | 'index' | 'urlset' | 'unknown' | 'error'
    discovered_via TEXT NOT NULL,        -- 'robots' | 'index_walk' | 'common_path'
    http_status INTEGER,
    fresh_entries_24h INTEGER,
    latest_pub_date TIMESTAMPTZ,
    etag TEXT,
    last_modified TEXT,                  -- HTTP Last-Modified header verbatim
    last_checked_at TIMESTAMPTZ NOT NULL,
    last_ok_at TIMESTAMPTZ,
    error TEXT,
    PRIMARY KEY (source_id, sitemap_url)
);

CREATE INDEX IF NOT EXISTS source_sitemap_kind ON sources.source_sitemap(kind);

CREATE TABLE IF NOT EXISTS sources.discovery_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    sources_checked INTEGER NOT NULL DEFAULT 0,
    news_sitemaps_found INTEGER NOT NULL DEFAULT 0,
    error TEXT
);

-- RSS / Atom feeds discovered per source. Per source we try:
--   1. `<link rel="alternate" type="application/(rss|atom|rdf)+xml">` in
--      the homepage HTML.
--   2. common paths (/feed, /rss, /feed.xml, /atom.xml, /index.xml)
--   3. Mediacloud feed_list as last-resort fallback (if MC API key present)
-- A feed only lands here after it parses as RSS / Atom / RDF.
CREATE TABLE IF NOT EXISTS sources.source_feed (
    source_id INTEGER NOT NULL REFERENCES sources.source(id) ON DELETE CASCADE,
    feed_url TEXT NOT NULL,
    kind TEXT NOT NULL,                  -- 'rss' | 'atom' | 'rdf' | 'error'
    discovered_via TEXT NOT NULL,        -- 'homepage_link' | 'common_path' | 'mediacloud'
    http_status INTEGER,
    title TEXT,
    latest_entry_date TIMESTAMPTZ,
    entries_seen INTEGER,
    etag TEXT,
    last_modified TEXT,
    last_checked_at TIMESTAMPTZ NOT NULL,
    last_ok_at TIMESTAMPTZ,
    error TEXT,
    PRIMARY KEY (source_id, feed_url)
);

CREATE INDEX IF NOT EXISTS source_feed_kind ON sources.source_feed(kind);
CREATE INDEX IF NOT EXISTS source_feed_discovered_via ON sources.source_feed(discovered_via);

CREATE TABLE IF NOT EXISTS sources.feed_discovery_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    sources_checked INTEGER NOT NULL DEFAULT 0,
    feeds_found INTEGER NOT NULL DEFAULT 0,
    mediacloud_fallbacks INTEGER NOT NULL DEFAULT 0,
    error TEXT
);
