-- Sentinel schema (singular table names).
-- Applied idempotently at startup by Database._create_tables().

-- App-level accounts (Google sign-in). `user` is a reserved word, so app_user.
-- Per-user classification criteria lives here too; notification targets are in
-- push_subscription (one row per registered browser/device).
CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_sub TEXT UNIQUE NOT NULL,
    email TEXT NOT NULL,
    name TEXT,
    criteria TEXT
);

-- Web Push subscriptions. A user installs the PWA on each device and enables
-- notifications, producing one subscription per device. endpoint is the push
-- service URL (unique identity); p256dh/auth are the client's encryption keys.
CREATE TABLE IF NOT EXISTS push_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    endpoint TEXT UNIQUE NOT NULL,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS push_subscription_user_idx ON push_subscription (user_id);

CREATE TABLE IF NOT EXISTS inbox (
    name TEXT PRIMARY KEY,
    config_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Multi-tenant: each inbox belongs to a user. Nullable for legacy rows;
-- the console always scopes by user_id. (Names are globally unique for now —
-- per-user name namespacing is a later cleanup.)
ALTER TABLE inbox ADD COLUMN IF NOT EXISTS user_id BIGINT REFERENCES app_user(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS inbox_user_idx ON inbox (user_id);

-- The core table. One row per observed message; also the dedup ledger.
-- source_id is the natural identity (inbox-namespaced message id) — the
-- UNIQUE constraint gives us cross-restart dedup for free. A row exists only
-- once a message reaches a terminal outcome (classified, or permanently failed).
CREATE TABLE IF NOT EXISTS message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Identity
    source_id TEXT NOT NULL,
    inbox_name TEXT NOT NULL,
    -- Content
    title TEXT NOT NULL,
    body TEXT,
    url TEXT,
    author TEXT,
    -- Two timestamps because they drift:
    --   received_at  = when the message was dated by the sender
    --   observed_at  = when sentinel wrote this row
    received_at TIMESTAMPTZ NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (source_id)
);

CREATE INDEX IF NOT EXISTS message_observed_at_idx ON message (observed_at DESC);
CREATE INDEX IF NOT EXISTS message_received_at_idx ON message (received_at DESC);
CREATE INDEX IF NOT EXISTS message_inbox_observed_idx ON message (inbox_name, observed_at DESC);

-- Per-message classification result. One row per message, present iff the
-- classifier ran successfully. This is purely the classifier's verdict and
-- provenance — whether that verdict turns into a user alert is a separate
-- concern, recorded in `notification`.
CREATE TABLE IF NOT EXISTS classification (
    message_id BIGINT PRIMARY KEY REFERENCES message(id) ON DELETE CASCADE,
    priority TEXT NOT NULL CHECK (priority IN ('important', 'normal')),
    reasoning TEXT,
    -- Provenance: which model produced this.
    model TEXT NOT NULL,
    classified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    latency_ms INTEGER
);

CREATE INDEX IF NOT EXISTS classification_classified_at_idx
    ON classification (classified_at DESC);
-- Partial index for listing important messages (the hot filter).
CREATE INDEX IF NOT EXISTS classification_important_idx
    ON classification (classified_at DESC) WHERE priority = 'important';

-- Classifier failures get their own table so we can retry without bloating
-- the success path. Same FK shape as classification.
CREATE TABLE IF NOT EXISTS classification_failure (
    message_id BIGINT PRIMARY KEY REFERENCES message(id) ON DELETE CASCADE,
    error TEXT NOT NULL,
    attempts SMALLINT NOT NULL DEFAULT 1,
    last_failed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- A notification is the decision to alert a user about a message — a distinct
-- object from the classification that triggered it. One row per (message, user)
-- the app intended to alert; `summary` is the user-facing alert text (lives here,
-- not on classification) and `status` is the delivery outcome. Web Push is the
-- only channel, so a 'skipped'/'failed' row is the visible record of a missed
-- alert that would otherwise vanish into the logs.
CREATE TABLE IF NOT EXISTS notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES message(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    summary TEXT,
    status TEXT NOT NULL CHECK (status IN ('sent', 'failed', 'skipped')),
    detail TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (message_id, user_id)
);

CREATE INDEX IF NOT EXISTS notification_user_created_idx
    ON notification (user_id, created_at DESC);
