-- Sentinel schema (singular table names).
-- Applied idempotently at startup by Database._create_tables().

CREATE TABLE IF NOT EXISTS schema_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- App-level accounts (Google sign-in). `user` is a reserved word, so app_user.
-- Per-user classification criteria + notification target live here too.
CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_sub TEXT UNIQUE NOT NULL,
    email TEXT NOT NULL,
    name TEXT,
    criteria TEXT,
    telegram_chat_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS stream (
    name TEXT PRIMARY KEY,
    stream_type TEXT NOT NULL,
    config_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Multi-tenant: each inbox belongs to a user. Nullable for legacy rows;
-- the console always scopes by user_id. (Names are globally unique for now —
-- per-user name namespacing is a later cleanup.)
ALTER TABLE stream ADD COLUMN IF NOT EXISTS user_id BIGINT REFERENCES app_user(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS stream_user_idx ON stream (user_id);

CREATE TABLE IF NOT EXISTS telegram_link_token (
    token TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL
);
-- The token records which user initiated the link, so the bot can bind the
-- chat_id to the right account on /start <token>.
ALTER TABLE telegram_link_token ADD COLUMN IF NOT EXISTS user_id BIGINT REFERENCES app_user(id) ON DELETE CASCADE;

-- The core table. One row per observed email; also the dedup ledger.
-- item_id is the natural identity (stream-namespaced message id) — the
-- UNIQUE constraint gives us cross-restart dedup for free. A row exists only
-- once an item reaches a terminal outcome (classified, or permanently failed).
CREATE TABLE IF NOT EXISTS event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Identity
    item_id TEXT NOT NULL,
    stream_name TEXT NOT NULL,
    -- Content
    title TEXT NOT NULL,
    body TEXT,
    url TEXT,
    author TEXT,
    -- Two timestamps because they drift:
    --   received_at  = when the message was dated by the sender
    --   observed_at  = when sentinel wrote this row
    received_at TIMESTAMPTZ NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Source-specific extras (provider, recipient, ...). JSONB so we can still
    -- spot-check via ->> when needed.
    metadata JSONB,
    UNIQUE (item_id)
);

CREATE INDEX IF NOT EXISTS event_observed_at_idx ON event (observed_at DESC);
CREATE INDEX IF NOT EXISTS event_received_at_idx ON event (received_at DESC);
CREATE INDEX IF NOT EXISTS event_stream_observed_idx ON event (stream_name, observed_at DESC);

-- Per-event classification result. One row per event, present iff the
-- classifier ran successfully.
CREATE TABLE IF NOT EXISTS classification (
    event_id BIGINT PRIMARY KEY REFERENCES event(id) ON DELETE CASCADE,
    priority TEXT NOT NULL CHECK (priority IN ('important', 'normal')),
    summary TEXT,
    reasoning TEXT,
    -- Provenance: which model produced this.
    model TEXT NOT NULL,
    classified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    latency_ms INTEGER
);

CREATE INDEX IF NOT EXISTS classification_classified_at_idx
    ON classification (classified_at DESC);
-- Partial index for listing important items (the hot filter).
CREATE INDEX IF NOT EXISTS classification_important_idx
    ON classification (classified_at DESC) WHERE priority = 'important';

-- Classifier failures get their own table so we can retry without bloating
-- the success path. Same FK shape as classification.
CREATE TABLE IF NOT EXISTS classification_failure (
    event_id BIGINT PRIMARY KEY REFERENCES event(id) ON DELETE CASCADE,
    error TEXT NOT NULL,
    attempts SMALLINT NOT NULL DEFAULT 1,
    last_failed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
