-- Sentinel local runtime schema (singular table names).
-- Applied idempotently at startup by LocalDatabase._create_tables().

CREATE TABLE IF NOT EXISTS schema_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app_setting (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS local_setting (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS stream (
    name TEXT PRIMARY KEY,
    stream_type TEXT NOT NULL,
    config_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS monitoring_state (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS telegram_link_token (
    token TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL
);

-- The core table. One row per observed item; replaces both the old
-- `live_events` event log and the `processed_items` dedup ledger.
-- (source_type, item_id) is the natural identity — uniqueness here gives
-- us cross-restart dedup for free.
CREATE TABLE IF NOT EXISTS event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Identity
    source_type TEXT NOT NULL,
    item_id TEXT NOT NULL,
    stream_name TEXT NOT NULL,
    -- Content
    title TEXT NOT NULL,
    -- body is nullable: for sources where it duplicates title (Bluesky) or
    -- where it's just reconstituted metadata (sitemap_news), we leave it null
    -- and consumers fall back to title.
    body TEXT,
    url TEXT,
    author TEXT,
    -- Two timestamps because they drift:
    --   received_at  = when the publisher dated the item (from XML/feed/post)
    --   observed_at  = when sentinel wrote this row
    received_at TIMESTAMPTZ NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Source-specific bag for anything we don't filter on (Bluesky lang,
    -- RSS feed_title, raw keywords list, ...). Use JSONB so we can still
    -- spot-check via ->> when needed.
    metadata JSONB,
    UNIQUE (source_type, item_id)
);

CREATE INDEX IF NOT EXISTS event_observed_at_idx ON event (observed_at DESC);
CREATE INDEX IF NOT EXISTS event_received_at_idx ON event (received_at DESC);
CREATE INDEX IF NOT EXISTS event_stream_observed_idx ON event (stream_name, observed_at DESC);
CREATE INDEX IF NOT EXISTS event_source_observed_idx ON event (source_type, observed_at DESC);

-- Per-event classification result. One row per event, present iff the
-- classifier ran successfully.
CREATE TABLE IF NOT EXISTS classification (
    event_id BIGINT PRIMARY KEY REFERENCES event(id) ON DELETE CASCADE,
    priority TEXT NOT NULL CHECK (priority IN ('important', 'normal')),
    summary TEXT,
    reasoning TEXT,
    -- Provenance: which model + prompt produced this; lets us reclassify
    -- selectively when either changes.
    model TEXT NOT NULL,
    prompt_version SMALLINT NOT NULL DEFAULT 1,
    classified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    latency_ms INTEGER
);

CREATE INDEX IF NOT EXISTS classification_classified_at_idx
    ON classification (classified_at DESC);
-- Partial index — `important` is ~10% of rows and is the hot filter on /alerts.
CREATE INDEX IF NOT EXISTS classification_important_idx
    ON classification (classified_at DESC) WHERE priority = 'important';

-- Classifier failures get their own table so we can retry without bloating
-- the success path. Same FK shape as classification.
CREATE TABLE IF NOT EXISTS classification_failure (
    event_id BIGINT PRIMARY KEY REFERENCES event(id) ON DELETE CASCADE,
    error TEXT NOT NULL,
    attempts SMALLINT NOT NULL DEFAULT 1,
    last_failed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
