-- One-shot migration to singular table names + typed `event`/`classification`
-- shape. Run inside a single transaction. Safe to re-run iff each step is
-- idempotent (CREATE IF NOT EXISTS, DROP IF EXISTS).
--
-- What this preserves:
--   - app_settings / local_settings (renamed, content preserved)
--   - streams (renamed, config_json becomes JSONB)
--   - monitoring_state (already singular, content preserved)
--   - schema_meta
--   - telegram_link_tokens (renamed singular)
--   - sources.* catalog (renamed singular + booleans cast + timestamps cast)
--
-- What this DROPS:
--   - live_events (the old append-only firehose log; not carried over —
--     the classification rows we cared about are migrated below)
--   - processed_items (the new event table's UNIQUE (source_type, item_id)
--     replaces this dedup ledger; migrated as event rows with no content)

BEGIN;

-- ---------- public schema ----------

-- app_setting (singular)
CREATE TABLE IF NOT EXISTS app_setting (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
INSERT INTO app_setting (key, value, updated_at)
SELECT key, value, COALESCE(updated_at, NOW()) FROM app_settings
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS local_setting (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
INSERT INTO local_setting (key, value, updated_at)
SELECT key, value, COALESCE(updated_at, NOW()) FROM local_settings
ON CONFLICT (key) DO NOTHING;

-- stream: config_json text -> jsonb
CREATE TABLE IF NOT EXISTS stream (
    name TEXT PRIMARY KEY,
    stream_type TEXT NOT NULL,
    config_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
INSERT INTO stream (name, stream_type, config_json, updated_at)
SELECT name, stream_type, config_json::jsonb, COALESCE(updated_at, NOW())
FROM streams
ON CONFLICT (name) DO NOTHING;

-- telegram_link_token (singular)
CREATE TABLE IF NOT EXISTS telegram_link_token (
    token TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL
);
INSERT INTO telegram_link_token (token, created_at, expires_at)
SELECT token, COALESCE(created_at, NOW()), expires_at FROM telegram_link_tokens
ON CONFLICT (token) DO NOTHING;

-- The new core table
CREATE TABLE IF NOT EXISTS event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type TEXT NOT NULL,
    item_id TEXT NOT NULL,
    stream_name TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT,
    url TEXT,
    author TEXT,
    received_at TIMESTAMPTZ NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    score REAL,
    metadata JSONB,
    UNIQUE (source_type, item_id)
);

CREATE INDEX IF NOT EXISTS event_observed_at_idx ON event (observed_at DESC);
CREATE INDEX IF NOT EXISTS event_received_at_idx ON event (received_at DESC);
CREATE INDEX IF NOT EXISTS event_stream_observed_idx ON event (stream_name, observed_at DESC);
CREATE INDEX IF NOT EXISTS event_source_observed_idx ON event (source_type, observed_at DESC);

-- Migrate processed_items into event (the dedup ledger keeps working without
-- a separate table). No body/url/score for these — they were dedup-only rows.
INSERT INTO event (source_type, item_id, stream_name, title, received_at, observed_at)
SELECT
    source_type,
    item_id,
    COALESCE(stream_name, ''),
    COALESCE(NULLIF(title, ''), item_id),  -- avoid NOT NULL violation; fall back to item_id
    COALESCE(processed_at, NOW()),
    COALESCE(processed_at, NOW())
FROM processed_items
ON CONFLICT (source_type, item_id) DO NOTHING;

-- We intentionally do NOT migrate live_events rows. The table is mostly
-- Bluesky firehose noise; the few useful item_classified rows re-accumulate
-- under the new code. Trying to migrate would also risk NUL-poisoned
-- payloads postgres can't cast.

-- Classifications go to a typed table now
CREATE TABLE IF NOT EXISTS classification (
    event_id BIGINT PRIMARY KEY REFERENCES event(id) ON DELETE CASCADE,
    priority TEXT NOT NULL CHECK (priority IN ('important', 'normal')),
    summary TEXT,
    reasoning TEXT,
    model TEXT NOT NULL,
    prompt_version SMALLINT NOT NULL DEFAULT 1,
    classified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    latency_ms INTEGER
);

CREATE INDEX IF NOT EXISTS classification_classified_at_idx
    ON classification (classified_at DESC);
CREATE INDEX IF NOT EXISTS classification_important_idx
    ON classification (classified_at DESC) WHERE priority = 'important';

CREATE TABLE IF NOT EXISTS classification_failure (
    event_id BIGINT PRIMARY KEY REFERENCES event(id) ON DELETE CASCADE,
    error TEXT NOT NULL,
    attempts SMALLINT NOT NULL DEFAULT 1,
    last_failed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- (No bulk migration of classifications either — the few we had get
--  regenerated by the running classifier in minutes.)

-- Drop the legacy public tables (new code never reads them)
DROP TABLE IF EXISTS app_settings;
DROP TABLE IF EXISTS local_settings;
DROP TABLE IF EXISTS streams;
DROP TABLE IF EXISTS telegram_link_tokens;
DROP TABLE IF EXISTS live_events;
DROP TABLE IF EXISTS processed_items;

-- ---------- sources schema ----------

-- We rename in place. Drop FKs from the renamed children before renaming the
-- parent to avoid PG complaining; we re-add them below.
-- (None of the old tables had FKs, so this is mostly forward-looking.)

ALTER TABLE IF EXISTS sources.collections             RENAME TO collection;
ALTER TABLE IF EXISTS sources.sources                 RENAME TO source;
ALTER TABLE IF EXISTS sources.source_collections      RENAME TO source_collection;
ALTER TABLE IF EXISTS sources.sync_runs               RENAME TO sync_run;
ALTER TABLE IF EXISTS sources.source_sitemaps         RENAME TO source_sitemap;
ALTER TABLE IF EXISTS sources.discovery_runs          RENAME TO discovery_run;
ALTER TABLE IF EXISTS sources.source_feeds            RENAME TO source_feed;
ALTER TABLE IF EXISTS sources.feed_discovery_runs     RENAME TO feed_discovery_run;

-- Boolean conversions
ALTER TABLE sources.collection
    ALTER COLUMN public    TYPE BOOLEAN USING (public    <> 0),
    ALTER COLUMN featured  TYPE BOOLEAN USING (featured  <> 0),
    ALTER COLUMN managed   TYPE BOOLEAN USING (managed   <> 0),
    ALTER COLUMN monitored TYPE BOOLEAN USING (monitored <> 0);

ALTER TABLE sources.source
    ALTER COLUMN monitored TYPE BOOLEAN USING (monitored <> 0);

-- Timestamp conversions where the column is cleanly ISO. We wrap in CASE
-- so empty strings or malformed values don't blow up the migration.
ALTER TABLE sources.collection
    ALTER COLUMN upstream_modified_at TYPE TIMESTAMPTZ USING
        CASE WHEN upstream_modified_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
             THEN upstream_modified_at::timestamptz ELSE NULL END,
    ALTER COLUMN last_refreshed_at TYPE TIMESTAMPTZ USING
        last_refreshed_at::timestamptz;

ALTER TABLE sources.source
    ALTER COLUMN upstream_created_at TYPE TIMESTAMPTZ USING
        CASE WHEN upstream_created_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
             THEN upstream_created_at::timestamptz ELSE NULL END,
    ALTER COLUMN upstream_modified_at TYPE TIMESTAMPTZ USING
        CASE WHEN upstream_modified_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
             THEN upstream_modified_at::timestamptz ELSE NULL END,
    ALTER COLUMN last_rescraped_at TYPE TIMESTAMPTZ USING
        CASE WHEN last_rescraped_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
             THEN last_rescraped_at::timestamptz ELSE NULL END,
    ALTER COLUMN last_refreshed_at TYPE TIMESTAMPTZ USING
        last_refreshed_at::timestamptz,
    ALTER COLUMN alternative_domains TYPE JSONB USING
        CASE WHEN alternative_domains IS NULL OR alternative_domains = ''
             THEN NULL ELSE alternative_domains::jsonb END;

ALTER TABLE sources.sync_run
    ALTER COLUMN started_at TYPE TIMESTAMPTZ USING started_at::timestamptz,
    ALTER COLUMN finished_at TYPE TIMESTAMPTZ USING
        CASE WHEN finished_at IS NULL OR finished_at = '' THEN NULL
             ELSE finished_at::timestamptz END;

ALTER TABLE sources.source_sitemap
    ALTER COLUMN latest_pub_date TYPE TIMESTAMPTZ USING
        CASE WHEN latest_pub_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
             THEN latest_pub_date::timestamptz ELSE NULL END,
    ALTER COLUMN last_checked_at TYPE TIMESTAMPTZ USING last_checked_at::timestamptz,
    ALTER COLUMN last_ok_at TYPE TIMESTAMPTZ USING
        CASE WHEN last_ok_at IS NULL OR last_ok_at = '' THEN NULL
             ELSE last_ok_at::timestamptz END;

ALTER TABLE sources.discovery_run
    ALTER COLUMN started_at TYPE TIMESTAMPTZ USING started_at::timestamptz,
    ALTER COLUMN finished_at TYPE TIMESTAMPTZ USING
        CASE WHEN finished_at IS NULL OR finished_at = '' THEN NULL
             ELSE finished_at::timestamptz END;

ALTER TABLE sources.source_feed
    ALTER COLUMN latest_entry_date TYPE TIMESTAMPTZ USING
        CASE WHEN latest_entry_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
             THEN latest_entry_date::timestamptz ELSE NULL END,
    ALTER COLUMN last_checked_at TYPE TIMESTAMPTZ USING last_checked_at::timestamptz,
    ALTER COLUMN last_ok_at TYPE TIMESTAMPTZ USING
        CASE WHEN last_ok_at IS NULL OR last_ok_at = '' THEN NULL
             ELSE last_ok_at::timestamptz END;

ALTER TABLE sources.feed_discovery_run
    ALTER COLUMN started_at TYPE TIMESTAMPTZ USING started_at::timestamptz,
    ALTER COLUMN finished_at TYPE TIMESTAMPTZ USING
        CASE WHEN finished_at IS NULL OR finished_at = '' THEN NULL
             ELSE finished_at::timestamptz END;

-- Index renames so they match the new table names
ALTER INDEX IF EXISTS sources.sources_canonical_domain RENAME TO source_canonical_domain;
ALTER INDEX IF EXISTS sources.sources_primary_language RENAME TO source_primary_language;
ALTER INDEX IF EXISTS sources.sources_pub_country      RENAME TO source_pub_country;
ALTER INDEX IF EXISTS sources.sources_stories_per_week RENAME TO source_stories_per_week;
ALTER INDEX IF EXISTS sources.source_sitemaps_kind     RENAME TO source_sitemap_kind;
ALTER INDEX IF EXISTS sources.source_feeds_kind        RENAME TO source_feed_kind;
ALTER INDEX IF EXISTS sources.source_feeds_discovered_via RENAME TO source_feed_discovered_via;

-- Bump schema version marker (cosmetic; nothing reads it yet)
INSERT INTO schema_meta (key, value)
VALUES ('schema_version', '2')
ON CONFLICT (key) DO UPDATE SET value = excluded.value;

COMMIT;
